#PROGRAM TO ASK FROM USER TO ISERT AN ELEMENT INTO LINKED LIST FROM BEGINNING ,END AND SPECIFIED POSITION.
while True:
    print("1.INSERT AT BEGINNING")
    print("2.INSERT AT END")
    print("3.INSERT AT SPECIFIED POSITION")
    print("4.EXIT")
    ch=int(input("ENTER YOUR CHOICE:"))

